- environment.tscn
- project.godot
> green colour

- environment.tscn
- project.godot
> changed project name + environment title

- Scenes/bullet.tscn
- Scenes/enemy.gd
- Scenes/enemy.tscn
- player.tscn
The bullet was way too large. I changed the scale of the bullet to not be as large. I also added a pistol to the enemy where the bullets come out of. Subject to change.
> fixed scale of the bullet, added pistol to enemy.

- Player.gd
Camera goes down when player crouches to simulate crouching.
> Added crouch functionality

- Player.gd
Added player health functionality code
> Player health functionality

- Scenes/enemy.gd
- Scenes/enemy.tscn
- Scenes/enemy_bullet.gd
- player.tscn
fixed enemy bullet collision issue
> Fixed enemy bullet collision issue and reset enemy speed

- main_menu.gd
- main_menu.tscn
- options.tscn
accidently duplicated menu (has been fixed)
> fixed menu node

- Player.gd
- Scenes/enemy.gd
- Scenes/enemy_bullet.gd
- Scenes/enemy_bullet.tscn
Changed var health in receive_damage to be current health.
Made enemy speed 0 and bullet speed 1 for testing purpose.
> changed player health

- Player.gd
- Scenes/enemy_bullet.gd
> Made the player take damage

- Player.gd
- Scenes/enemy_bullet.gd
Semi fixed player health, health bar still needs to be updated.
> Removed unneeded extra health function

- Scenes/enemy.gd
- Scenes/enemy_bullet.gd
- player_bullet.gd
Removed debug lines and changed enemy/enemy bullet movement speed
> updated speed

- Player.gd
- Scenes/enemy_bullet.gd
changed the naming scheme to be more consistent
> consistent naming

- Scenes/Player/player_bullet.gd
- Scenes/Player/player_bullet.tres
- Scenes/Player/player_bullet.tscn
player bullet is hopefully finalised
> Changed player bullet

- Scenes/Player/Player.gd
- Scenes/Player/player.tscn
- Scenes/options.gd
The player regenerates 1 health point per second
> Added health regeneration 

- Scenes/Enemy/enemy_bullet.tscn
- Scenes/Player/player_bullet.tscn
Appearance of bullet and enemy bullet as well
> Changed bullet again

- Scenes/Player/Player.gd
- Scenes/Worlds/testWorld.tscn
- Scenes/pickup.gd
- Scenes/pickup.tscn
added pickups to the game, currently adds 1 when you collide with it
> Added pickups

- Scenes/Enemy/enemy.gd
Enemy's will now only fire and move towards the player if the player go's within a 10m radius of them
> Updated enemy movement

- Scenes/Enemy/enemy.gd
- Scenes/Player/Player.gd
- Scenes/Worlds/spaceshipMap.tscn
- Scenes/Worlds/testWorld.tscn
- project.godot
Enemies will follow the player indefinitely after the player has entered anywhere in a 10m radius of the enemy.
> Enemie movement update

- Scenes/Player/Player.gd
made the player script more legible
> cleaned player script

- Scenes/Worlds/spaceshipMap.tscn
- Scenes/spawner.gd
- Scenes/spawner.tscn
- Scripts/enemy_2.tscn
- enemy_2.gd
wave manager now spawns off marker positions rather than the original node, and now can spawn multiple types of enemies
> wave manager changes

- Scenes/Enemy/enemy.gd
- Scenes/Enemy/enemy.tscn
- Scenes/Player/player.tscn
> fixed gun position and enemy animation

- Scenes/Enemy/enemy.gd
- Scenes/Enemy/enemy_2.tscn
- Scenes/Player/Player.gd
- Scenes/Player/player.tscn
- Scenes/Worlds/spaceshipMap.tscn
- Scenes/enemy_2.gd
- Scenes/spawner.gd
- Scenes/spawner.tscn
- project.godot
> pull request

- Scenes/Worlds/main_menu.gd
- Scenes/Worlds/main_menu.tscn
- Scenes/Worlds/spaceshipMap.tscn
- Scenes/Worlds/spaceship_map.gd
- Scripts/Global.gd
- audio/Credits 2.ogg.import
This PR implements Multiplayer functionality in the base game.
The main menu has been modified to include Host and a Join button, including an input box for IP address.
Has not been fully tested.
> Multiplayer Functionality

- Scenes/Player/Player.gd
- Scenes/Player/player.tscn
- Scenes/Worlds/main_menu.tscn
Issue: get_tree().add_child(pistol_bullet) caused the game to crash Solution:
Commented out get_tree().add_child(pistol_bullet)
> Fixed crash on shoot

- Scenes/Player/Player.gd
set ammo for weapons to maximum amount
> weapons reload when you respawn

- Scenes/Worlds/spaceship_map.gd
- Scenes/pause menu/paused_menu.gd
- Scenes/pause menu/paused_menu.tscn
ip now shows in the pause menu
> pause menu ip

- Scenes/Player/Player.gd
yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! yay! …
> Multiplayer Animations Work!!!
